variable "function_name" {
  default     = null
  description = "Base logical name for this deployment. Used directly as the Lambda function name, and to derive default names for every other resource (IAM role/policy, DynamoDB table) — override any of those individually via their own *_name variable below if you don't want the derived default. Defaults to \"github-pr-slack-notifier-<github_username>\" so multiple people's instances can coexist in one AWS account without a name collision."
  type        = string
}

variable "github" {
  description = "The GitHub App's credentials, grouped into one object since app_id/app_private_key/webhook_secret are each referenced in exactly one place (lambda.tf's environment block) and nowhere else — a tight, single-purpose bundle. github_username/github_org_allowlist stay as their own top-level variables instead, since github_username is also load-bearing in locals.tf (function-name default, Description/Owner tags) and github_org_allowlist is deployment-scope config, not an App credential. Marked sensitive as a whole because app_private_key/webhook_secret are real secrets — Terraform can't mark sensitivity per-attribute within one object variable, so this also hides app_id (not actually sensitive) from plan output, an accepted tradeoff. `app_id` is the GitHub App's numeric ID. `app_private_key` is its PEM-encoded RSA private key. `webhook_secret` verifies inbound webhook signatures (SEC-002)."
  sensitive   = true
  type = object({
    app_id          = string
    app_private_key = string
    webhook_secret  = string
  })
}

variable "github_org_allowlist" {
  description = "GitHub organizations this deployment watches (REQ-009). The GitHub App must also be installed on each of these orgs for events to arrive at all."
  type        = list(string)
}

variable "github_username" {
  description = "GitHub login whose subscriptions are evaluated (REQ-001)."
  type        = string
}

variable "iam_role_name" {
  default     = null
  description = "Name of the Lambda's IAM role. Defaults to PascalCase(function_name) + \"Role\" (e.g. \"GithubPrSlackNotifierRole\"), matching this repo's IAM naming convention."
  type        = string
}

variable "lambda_function_name" {
  default     = null
  description = "Name of the Lambda function. Defaults to function_name as-is."
  type        = string
}

variable "lambda_source" {
  default     = {}
  description = "Controls where the Lambda's code comes from, via three priority tiers evaluated in order: (1) `zip_path` (default `\"../../dist/lambda.zip\"`, i.e. `task build`'s output) resolves to a real local file — always wins, an explicit \"I'm actively changing the code and testing it\" signal, so it overrides everything else even if `github_release_version` is also set. (2) `zip_path` doesn't resolve to a file, and `github_release_version` (default `null`) is non-null — the module downloads that git tag's `lambda.zip` GitHub Release asset from `github_release_repo` itself, for appliers with no local build at all (e.g. a non-interactive CI/Spacelift runner); leaving `github_release_version` null disables this tier entirely. (3) `zip_path` doesn't resolve AND `github_release_version` is `null` — the module falls back to whatever code is already deployed, making `plan`/`apply` a silent no-op; this is also what a first-ever apply falls back to if it has neither a local build nor `github_release_version` set, and since no function exists yet to fall back to, that first apply fails. `github_release_repo` (default `\"emmahsax/github-pr-slack-notifier\"`) is the GitHub \"owner/repo\" `github_release_version`'s tag lives in — override it if you're running from a fork (this repo's README explicitly invites forking), otherwise you'll silently deploy someone else's build instead of yours; it has no effect when `github_release_version` is null. Keep `github_release_version` in sync with whatever tag this module call's own `source = \"...?ref=<tag>\"` is pinned to — Terraform can't read its own source ref, AND `source` itself must be a literal string (Terraform resolves a module's source address during `terraform init`, before any locals/variables are evaluated, so not even a shared `local` can bridge the two), so both have to be set to the same literal value by hand, independently, rather than one being inferred from or generated by the other. Whichever of `zip_path` or `github_release_version` is active mirrors its zip's bytes into Terraform state (see `lambda_deploy.tf`) — expect a plan/state-size cost proportional to the zip's size (a few MB) on every apply where either is active, even when the content hasn't changed. `github_release_version` specifically also costs a real network fetch on every single `plan`/`apply` where it's set, since Terraform re-fetches data sources on every plan regardless of whether the version changed; `zip_path` has no such recurring cost, since reading a local file at plan time isn't a data source."
  type = object({
    github_release_repo    = optional(string, "emmahsax/github-pr-slack-notifier")
    github_release_version = optional(string)
    zip_path               = optional(string, "../../dist/lambda.zip")
  })
}

variable "slack" {
  description = "Slack delivery configuration, grouped into one object since target's relevance depends on delivery_method's value (unused for \"incoming_webhook\", required for \"bot_token\"). Marked sensitive as a whole because credential is a real secret (bot token or webhook URL) — Terraform can't mark sensitivity per-attribute within one object variable, so this also hides delivery_method/target (not actually sensitive) from plan output, an accepted tradeoff. `credential` is the Slack bot token or incoming webhook URL, whichever `delivery_method` selects. `delivery_method` is either \"bot_token\" (chat.postMessage, supports grouping a PR's activity into one Slack thread per REQ-015) or \"incoming_webhook\" (fixed-channel webhook, always flat messages per REQ-017 — Slack's incoming webhooks never return a message ts to thread against). `target` is the Slack channel ID (e.g. a dedicated \"my-prs\" channel, with the bot invited) or user ID to DM — required when `delivery_method` is \"bot_token\"; unused otherwise (the destination is baked into the webhook URL)."
  sensitive   = true
  type = object({
    credential      = string
    delivery_method = string
    target          = optional(string, "")
  })

  validation {
    condition     = contains(["bot_token", "incoming_webhook"], var.slack.delivery_method)
    error_message = "slack.delivery_method must be \"bot_token\" or \"incoming_webhook\"."
  }
}

variable "tags" {
  default     = {}
  description = "Tags merged into every resource this module creates. Description/ManagedBy/Owner/Region get sensible defaults automatically (see locals.tf) if not set here, and can be overridden by setting the same key — e.g. tags = { Owner = \"someone-else\", Environment = \"Personal\" }. Name/ResourceType can never be overridden here; they always reflect the actual resource."
  type        = map(string)

  validation {
    # AWS tag values only allow letters/numbers/spaces plus . : / = + - @
    # (IAM's error on an invalid tag value spells out the exact regex) — no
    # commas or other punctuation, and this applies across AWS services,
    # not just IAM, so every value is checked regardless of key.
    condition     = alltrue([for v in values(var.tags) : can(regex("^[\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*$", v))])
    error_message = "All tag values must only contain characters valid in AWS tags: letters, numbers, spaces, and . : / = + - @ (no commas or other punctuation)."
  }
}

variable "thread_store_policy_name" {
  default     = null
  description = "Name of the IAM inline policy granting the Lambda access to the thread-store DynamoDB table (only created when slack.delivery_method is \"bot_token\"). Defaults to PascalCase(function_name) + \"ThreadStorePolicy\"."
  type        = string
}

variable "thread_store_table_name" {
  default     = null
  description = "Name of the DynamoDB table grouping a PR's notifications into one Slack thread (only created when slack.delivery_method is \"bot_token\"). Defaults to function_name + \"-threads\"."
  type        = string
}
